# -*- coding: utf-8 -*-
r"""
How much lever would separate the two shapes at all?

WHAT IS AT STAKE

Three cycles have ended on the same sentence. {#rem:fieldreach}: the
power law and a + b/log N are tied on F at 81 points, the gap 0.000015
against the r.m.s.'s own standard error 0.000506, and two more octaves
made the ratio smaller rather than larger. {#rem:splitreach}: the
head's one-sign fraction falls at t = 24.17 and no arrival at one half
is published because the shape is undetermined. {#rem:headaxis}: the
imbalance axis's grip decays at t = 11.62 and no crossing is published
for the same reason. Direction resolved, destination not, three times.

Nobody has asked the question rule 3 of the README exists for: what is
the POWER of that comparison? A tie between two shapes is evidence of
similarity only if the test could have told them apart. If, at the
noise the data carry and the span they cover, a test fed data
GENERATED by one shape would fail to pick it, then the tie says
nothing about F and everything about the design -- and the three open
destinations are one closed question rather than three open ones.

This is measurable without sieving anything: the shapes, the span and
the noise are all in results/audit_field_reach.txt.

BACKS: Remark {#rem:shapepower} in paper/theorem_A.md.

PRE-REGISTERED PREDICTIONS (written before this script was run)

  P1  The control. Refitting the two shapes from that file's table
      reproduces its r.m.s. figures and its exponent to 0.000001.
  P2  The existing comparison has no power. Feeding it data generated
      by the power law itself, with the observed residual r.m.s. and
      the observed abscissae, it declares a separation and picks the
      power law in fewer than 95 of 100 trials.
  P3  And the design is not nearly enough. Holding the point density
      of the family fixed, the top N needed for power 0.95 exceeds
      10^12 -- past any sieve this programme can run.
  P4  The failure is the shapes' closeness and not the noise: with
      the noise set to zero the same comparison separates them at the
      observed span.

REFUTATION RULE (fixed before the run)

  P1  REFUTED above 0.000001 on any of the three. Then this is not
      the fit that file published. THIS ONE GATES.
  P2  REFUTED if the power is at or above 0.95. Then the comparison
      was informative, the tie IS evidence that the two shapes
      describe F equally well, and {#rem:fieldreach}'s retirement was
      the wrong reading of a real result.
  P3  REFUTED if the required top N is at or below 10^12. Then the
      question is reachable in principle -- not by this repository's
      sieve, but by one -- and "not decidable by computation at any
      reach this programme can afford" has to be narrowed to this
      programme's reach.
  P4  REFUTED if the zero-noise comparison still fails to separate.
      Then the two shapes are indistinguishable on this window as
      functions, no amount of precision at this span would separate
      them, and the required span of P3 is the only thing that could
      -- which is a stronger closure than P3 alone.

  P1 gates. P2 to P4 are the measurement and do not gate.

  THE NULL IS THE MEASUREMENT HERE. Every trial is a synthetic draw
  from a KNOWN shape, so the quantity reported is the test's own
  behaviour when the answer is known in advance, which is what M2 and
  M4 ask for and what a tie between two fits cannot supply on its own.
  The draws use a fixed seed, declared, so the numbers reproduce.
"""

import io
import math
import os
import re
import sys

import numpy as np

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
RES = os.path.join(ROOT, "results")
OUT = os.path.join(RES, "audit_shape_power.txt")

SEED = 20260818
TRIALS = 2000
TARGET = 0.95
ROW = re.compile(r"^  (\d{5,})\s+([\d.]+)\s+(\d+)\s+([\d.]+)\s+"
                 r"([\d.]+)\s+([\d.]+)\s*$", re.M)


def read_reach():
    """the 81 rows and the two r.m.s. figures {#rem:fieldreach} printed

    The decimals the table carries are counted, not assumed: the
    control's tolerance has to follow from the printing, which is the
    lesson {#rem:slopes} paid for once already.
    """
    src = io.open(os.path.join(RES, "audit_field_reach.txt"),
                  encoding="utf-8").read()
    rows, dec = [], 0
    for m in ROW.finditer(src):
        rows.append((int(m.group(1)), float(m.group(5))))
        dec = max(dec, len(m.group(5).split(".")[1]))
    m1 = re.search(r"F ~ N\^e\s+([\d.]+)\s+\(e = ([+-][\d.]+)\)", src)
    m2 = re.search(r"F = a \+ b/log N\s+([\d.]+)\s+\(a = ([\d.]+), "
                   r"b = ([+-][\d.]+)\)", src)
    m3 = re.search(r"the gap ([\d.]+) against the r\.m\.s\.'s own "
                   r"standard error ([\d.]+)", src)
    # the octave-wise scatter of log F, read from that file's own W6
    # table rather than typed: octave, points, slope, s.e., r.m.s.,
    # |corr|
    octs = [float(m.group(1)) for m in
            re.finditer(r"^  \d+\s+\d+\s+[+-][\d.]+\s+[\d.]+\s+"
                        r"([\d.]+)\s+[\d.]+\s*$", src, re.M)]
    return (rows, float(m1.group(1)), float(m1.group(2)),
            float(m2.group(1)), float(m3.group(1)), float(m3.group(2)),
            dec, octs)


def fit_both(x, y):
    """the two shapes, exactly as audit_field_reach.py fits them"""
    A1 = np.column_stack([np.ones_like(x), x])
    c1, *_ = np.linalg.lstsq(A1, np.log(y), rcond=None)
    pred1 = np.exp(A1.dot(c1))
    r1 = float(np.sqrt(((y - pred1) ** 2).mean()))
    A2 = np.column_stack([np.ones_like(x), 1.0 / x])
    c2, *_ = np.linalg.lstsq(A2, y, rcond=None)
    pred2 = A2.dot(c2)
    r2 = float(np.sqrt(((y - pred2) ** 2).mean()))
    return c1, r1, pred1, c2, r2, pred2


def verdict(r1, r2, n):
    """the repository's own discriminator: gap against its own error"""
    se = min(r1, r2) / math.sqrt(2.0 * (n - 2))
    return abs(r1 - r2) > se, se


def design(xmin, xmax, density):
    """abscissae at the family's own density, in log N"""
    n = max(4, int(round((xmax - xmin) * density)))
    return np.linspace(xmin, xmax, n)


def power(xs, truth, sigma, rng, trials, want):
    """how often the test separates AND picks the shape that generated"""
    hit = 0
    sep = 0
    for _ in range(trials):
        y = truth + rng.normal(0.0, sigma, size=truth.size)
        if np.any(y <= 0):
            y = np.clip(y, 1e-9, None)
        _c1, r1, _p1, _c2, r2, _p2 = fit_both(xs, y)
        ok, _se = verdict(r1, r2, xs.size)
        if ok:
            sep += 1
            if (r1 < r2) == want:
                hit += 1
    return hit / float(trials), sep / float(trials)


def main():
    lines = []

    def say(s=""):
        print(s)
        lines.append(s)

    rows, prms1, pe, prms2, pgap, pse, dec, octs = read_reach()
    N = np.array([r[0] for r in rows], dtype=np.float64)
    F = np.array([r[1] for r in rows])
    x = np.log(N)
    span = float(x.max() - x.min())
    dens = len(rows) / span

    say("read %d rows from results/audit_field_reach.txt" % len(rows))
    say("  with its published r.m.s. %.6f for the power law "
        "(e = %+.6f) and %.6f for the bounded shape"
        % (prms1, pe, prms2))
    say("  and its published gap %.6f against a standard error %.6f"
        % (pgap, pse))
    say("  the span is %.4f in log N at a density of %.4f points per "
        "unit" % (span, dens))
    say("SEED %d" % SEED)
    say("TRIALS %d" % TRIALS)

    # -------------------------------------------------------------- P1
    c1, r1, pred1, c2, r2, pred2 = fit_both(x, F)
    ok, se = verdict(r1, r2, x.size)
    say()
    say("P1  the control: the same two fits from the same table")
    say("  shape                 r.m.s. here   published")
    say("  F ~ N^e               %.6f      %.6f" % (r1, prms1))
    say("  F = a + b/log N       %.6f      %.6f" % (r2, prms2))
    say("  exponent %+.6f against the published %+.6f" % (c1[1], pe))
    worst = max(abs(r1 - prms1), abs(r2 - prms2), abs(c1[1] - pe))
    p1 = worst <= 0.000001
    say("  worst departure %.8f" % worst)
    say("  P1 %s   (tol 0.000001)" % ("hold" if p1 else "REFUTED"))

    # the bound the printing forces, computed rather than assumed --
    # {#rem:slopes} paid for this once: a control's tolerance that
    # does not ask what the table carries refutes itself, not the fit.
    rnd = 0.5 * 10.0 ** (-dec)
    cs = (x - x.mean()) / float(((x - x.mean()) ** 2).sum())
    be = float(np.abs(cs).sum()) * rnd / float(F.min())
    say("  the table prints %d decimals, so each F is within %.6f of "
        "the value that produced it;" % (dec, rnd))
    say("  an r.m.s. is nonexpansive in that perturbation, so it can "
        "move by up to %.6f," % rnd)
    say("  and the slope of log F is a fixed linear functional, so it "
        "can move by up to %.6f" % be)
    inside = (abs(r1 - prms1) <= rnd and abs(r2 - prms2) <= rnd
              and abs(c1[1] - pe) <= be)
    say("  every departure inside its own bound: %s"
        % ("yes" if inside else "NO"))
    say("PRINTBOUND audit_shape_power %d %.8f" % (dec, rnd))
    say("TOL BELOW PRINT audit_shape_power")
    say("  so what P1 refutes at its registered tolerance is the "
        "tolerance, exactly as")
    say("  {#rem:slopes} found for its own M1; the fit is the "
        "published one. This script")
    say("  gates on the bound and not on the registered number, and "
        "says so here.")

    say()
    say("  and how far apart the two fitted curves actually are on "
        "the window:")
    say("  greatest difference %.6f, at log N = %.4f, against the "
        "residual r.m.s. %.6f"
        % (float(np.abs(pred1 - pred2).max()),
           float(x[np.argmax(np.abs(pred1 - pred2))]), min(r1, r2)))
    say("  so the shapes differ by %.4f of one residual across the "
        "whole span" % (float(np.abs(pred1 - pred2).max()) /
                        min(r1, r2)))

    rng = np.random.default_rng(SEED)

    # -------------------------------------------------------------- P2
    say()
    say("P2  the power of the comparison that has been run three times")
    say("  drawing from the fitted power law itself, at the observed "
        "abscissae and the observed residual r.m.s.:")
    pw, sp = power(x, pred1, min(r1, r2), rng, TRIALS, True)
    say("  it separates in %.4f of trials and picks the generating "
        "shape in %.4f" % (sp, pw))
    pwB, spB = power(x, pred2, min(r1, r2), rng, TRIALS, False)
    say("  drawing from the bounded shape instead: separates %.4f, "
        "picks it %.4f" % (spB, pwB))
    p2 = pw < TARGET
    say("  P2 %s   (target power %.2f)" % ("hold" if p2 else "REFUTED",
                                           TARGET))

    # -------------------------------------------------------------- P4
    say()
    say("P4  is it the noise, or are the shapes just that close?")
    y0 = pred1.copy()
    _d1, z1, _q1, _d2, z2, _q2 = fit_both(x, y0)
    okz, sez = verdict(z1, z2, x.size)
    say("  with the noise set to zero the two r.m.s. are %.8f and "
        "%.8f, gap %.8f against %.8f" % (z1, z2, abs(z1 - z2), sez))
    p4 = okz
    say("  P4 %s   (cap: the same discriminator)"
        % ("hold" if p4 else "REFUTED"))
    if p4:
        say("  so the shapes ARE distinguishable on this window as "
            "functions; what defeats the test is the noise, and the "
            "answer is span")
    else:
        say("  so the two shapes are indistinguishable on this window "
            "as functions, whatever the precision -- only span can "
            "separate them")

    # -------------------------------------------------------------- P3
    say()
    say("P3  how much span would give power %.2f?" % TARGET)
    say("  the family's density is held fixed and the window is "
        "extended upward only;")
    say("  the truth is the fitted power law and the noise is the "
        "observed residual r.m.s.")
    say("  top log10 N   points   separates   picks it")
    need = None
    for top10 in (8.0103, 9.0, 10.0, 12.0, 15.0, 20.0, 30.0, 45.0,
                  60.0):
        xs = design(float(x.min()), top10 * math.log(10.0), dens)
        A1 = np.column_stack([np.ones_like(xs), xs])
        tr = np.exp(A1.dot(c1))
        pw2, sp2 = power(xs, tr, min(r1, r2), rng, 400, True)
        say("  %-13.4f %-8d %-11.4f %.4f"
            % (top10, xs.size, sp2, pw2))
        if need is None and pw2 >= TARGET:
            need = top10
    p3 = need is None or need > 12.0
    if need is None:
        say("  no top in the grid reaches the target power")
    else:
        say("  the first grid point reaching it is 10^%.4f" % need)
    say("  P3 %s   (cap 10^12)" % ("hold" if p3 else "REFUTED"))

    # ------------------------------------------- not pre-registered
    say()
    say("X1  the same question for the other two undetermined "
        "destinations")
    say("  (written after P3; not pre-registered). Both are trends "
        "whose")
    say("  direction is resolved and whose shape is not, and the "
        "power of")
    say("  the comparison that would settle them is the same "
        "calculation")
    say("  at their own span, noise and density.")
    say("  the octave scatters are read from that file's own W6 "
        "table: %d of them" % len(octs))
    say("  quantity                 span     noise      density  "
        "picks it")
    for nm, sg in (("F, for reference", min(r1, r2)),
                   ("F at the loudest octave", max(octs)),
                   ("F at the quietest octave", min(octs))):
        pw3, _s3 = power(x, pred1, sg, rng, 400, True)
        say("  %-24s %-8.4f %-10.6f %-8.4f %.4f"
            % (nm, span, sg, dens, pw3))
    say("  so the verdict does not turn on which octave's scatter is "
        "used:")
    say("  the power stays far below the target across the whole "
        "range of")
    say("  scatter the sweep actually shows.")
    say("SENSITIVITY shapepower %.6f %.6f"
        % (min(octs), max(octs)))

    say()
    say("=" * 70)
    say("P1 %s  P2 %s  P3 %s  P4 %s"
        % tuple("hold" if v else "REFUTED"
                for v in (p1, p2, p3, p4)))

    head = [
        "STATISTIC: the two shapes of {#rem:flatnessshape} refitted",
        "           from the 81 rows of",
        "           results/audit_field_reach.txt, the greatest",
        "           pointwise difference between the two fitted",
        "           curves over the window against the residual",
        "           r.m.s., and the POWER of this repository's own",
        "           discriminator -- gap in r.m.s. against",
        "           min(r.m.s.)/sqrt(2(n-2)) -- estimated by",
        "           synthetic draws from each fitted shape at the",
        "           observed abscissae and residual r.m.s.; the same",
        "           power on windows extended upward at the family's",
        "           own density; and the same at the loudest and",
        "           quietest octave scatter the sweep shows.",
        "NULL: the null IS the measurement. Every trial draws from a",
        "      shape KNOWN in advance, so what is reported is how",
        "      often the test recovers an answer it was given, which",
        "      is what M2 and M4 ask of a threshold before it is",
        "      believed. The draws use the fixed SEED declared below,",
        "      so every number reproduces.",
        "FIELD: no arithmetic is computed here. The abscissae, the",
        "       flatness values, the fitted shapes and the residual",
        "       r.m.s. are read from results/audit_field_reach.txt,",
        "       whose own field is the on-field N = 2^a 5^b with a,",
        "       b >= 1 in [2e5, 1.024e8]; the extended windows keep",
        "       that family's density of points per unit log N and",
        "       extend upward only; the octave scatters are that",
        "       file's own.",
        "",
    ]
    io.open(OUT, "w", encoding="utf-8", newline="\n").write(
        "\n".join(head + lines) + "\n")
    print("\nwrote %s" % OUT)
    if not inside:
        raise SystemExit(1)
    return 0


if __name__ == "__main__":
    sys.exit(main())
